namespace PyRough.Native.Python310;

#pragma warning disable CS0649 

internal unsafe partial class Python310ApiTable : ApiTable
{
    public Python310ApiTable(nint module) : base(module)
    {
    }

    [Import] public delegate* unmanaged[Cdecl]<nuint, void*> PyMem_Malloc;
    [Import] public delegate* unmanaged[Cdecl]<nuint, nuint, void*> PyMem_Calloc;
    [Import] public delegate* unmanaged[Cdecl]<void*, nuint, void*> PyMem_Realloc;
    [Import] public delegate* unmanaged[Cdecl]<void*, void> PyMem_Free;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> Py_Is;
    [Import] public delegate* unmanaged[Cdecl]<PyType_Spec*, _PyObject*> PyType_FromSpec;
    [Import] public delegate* unmanaged[Cdecl]<PyType_Spec*, _PyObject*, _PyObject*> PyType_FromSpecWithBases;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, int, void*> PyType_GetSlot;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, PyType_Spec*, _PyObject*, _PyObject*> PyType_FromModuleAndSpec;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _PyObject*> PyType_GetModule;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, void*> PyType_GetModuleState;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _PyTypeObject*, int> PyType_IsSubtype;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, uint> PyType_GetFlags;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, int> PyType_Ready;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, long, _PyObject*> PyType_GenericAlloc;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _PyObject*, _PyObject*, _PyObject*> PyType_GenericNew;
    [Import] public delegate* unmanaged[Cdecl]<uint> PyType_ClearCache;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, void> PyType_Modified;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_Repr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_Str;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_ASCII;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_Bytes;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int, _PyObject*> PyObject_RichCompare;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int, int> PyObject_RichCompareBool;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> PyObject_GetAttrString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*, int> PyObject_SetAttrString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyObject_HasAttrString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyObject_GetAttr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, int> PyObject_SetAttr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyObject_HasAttr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_SelfIter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyObject_GenericGetAttr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, int> PyObject_GenericSetAttr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, void*, int> PyObject_GenericSetDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyObject_Hash;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyObject_HashNotImplemented;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyObject_IsTrue;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyObject_Not;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyCallable_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> PyObject_ClearWeakRefs;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_Dir;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> Py_ReprEnter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> Py_ReprLeave;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _Py_Dealloc;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> Py_IncRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> Py_DecRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _Py_IncRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _Py_DecRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> Py_NewRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> Py_XNewRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> Py_IsNone;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _Py_NewReference;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, sbyte*> _PyType_Name;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _PyObject*, _PyObject*> _PyType_Lookup;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _Py_Identifier*, _PyObject*> _PyType_LookupId;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, _PyObject*> _PyObject_LookupSpecial;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _PyObject*, _PyTypeObject*> _PyType_CalculateMetaclass;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, _PyObject*> _PyType_GetDocFromInternalDoc;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, _PyObject*> _PyType_GetTextSignatureFromInternalDoc;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, PyModuleDef*, _PyObject*> _PyType_GetModuleByDef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _iobuf*, int, int> PyObject_Print;
    [Import] public delegate* unmanaged[Cdecl]<void> _Py_BreakPoint;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _PyObject_Dump;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyObject_IsFreed;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyObject_IsAbstract;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, _PyObject*> _PyObject_GetAttrId;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, _PyObject*, int> _PyObject_SetAttrId;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject**, int> _PyObject_LookupAttr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, _PyObject**, int> _PyObject_LookupAttrId;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject**, int> _PyObject_GetMethod;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject**> _PyObject_GetDictPtr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> _PyObject_NextNotImplemented;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> PyObject_CallFinalizer;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyObject_CallFinalizerFromDealloc;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, int, _PyObject*> _PyObject_GenericGetAttrWithDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*, int> _PyObject_GenericSetAttrWithDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> _PyObject_FunctionStr;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, nuint, void> _PyDebugAllocatorStats;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, void> _PyObject_DebugTypeStats;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, sbyte*, int, sbyte*, void> _PyObject_AssertFailed;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, int> _PyObject_CheckConsistency;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _PyTrash_deposit_object;
    [Import] public delegate* unmanaged[Cdecl]<void> _PyTrash_destroy_chain;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _PyTrash_thread_deposit_object;
    [Import] public delegate* unmanaged[Cdecl]<void> _PyTrash_thread_destroy_chain;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, _PyObject*, int> _PyTrash_begin;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, void> _PyTrash_end;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, delegate* unmanaged[Cdecl]<_PyObject*, void>, int> _PyTrash_cond;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, Double, long> _Py_HashDouble;
    [Import] public delegate* unmanaged[Cdecl]<void*, long> _Py_HashPointer;
    [Import] public delegate* unmanaged[Cdecl]<void*, long> _Py_HashPointerRaw;
    [Import] public delegate* unmanaged[Cdecl]<void*, long, long> _Py_HashBytes;
    [Import] public delegate* unmanaged[Cdecl]<PyHash_FuncDef*> PyHash_GetFuncDef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyByteArray_FromObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyByteArray_Concat;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, _PyObject*> PyByteArray_FromStringAndSize;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyByteArray_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyByteArray_AsString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PyByteArray_Resize;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, _PyObject*> PyBytes_FromStringAndSize;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyBytes_FromString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyBytes_FromObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, _PyObject*> PyBytes_FromFormatV;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyBytes_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyBytes_AsString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> PyBytes_Repr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, _PyObject*, void> PyBytes_Concat;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, _PyObject*, void> PyBytes_ConcatAndDel;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, long, sbyte*, _PyObject*> PyBytes_DecodeEscape;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte**, long*, int> PyBytes_AsStringAndSize;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, long, int> _PyBytes_Resize;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, _PyObject*, int, _PyObject*> _PyBytes_FormatEx;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> _PyBytes_FromHex;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, sbyte**, _PyObject*> _PyBytes_DecodeEscape;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> _PyBytes_Join;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, void> _PyBytesWriter_Init;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, void*, _PyObject*> _PyBytesWriter_Finish;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, void> _PyBytesWriter_Dealloc;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, long, void*> _PyBytesWriter_Alloc;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, void*, long, void*> _PyBytesWriter_Prepare;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, void*, long, void*> _PyBytesWriter_Resize;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, void*, void*, long, void*> _PyBytesWriter_WriteBytes;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, _PyObject*> PyUnicode_FromStringAndSize;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyUnicode_FromString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, _PyObject*> PyUnicode_Substring;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, uint*, long, int, uint*> PyUnicode_AsUCS4;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, uint*> PyUnicode_AsUCS4Copy;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyUnicode_GetLength;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyUnicode_GetSize;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, uint> PyUnicode_ReadChar;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, uint, int> PyUnicode_WriteChar;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, long, int> PyUnicode_Resize;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, _PyObject*> PyUnicode_FromEncodedObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_FromObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, _PyObject*> PyUnicode_FromFormatV;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, void> PyUnicode_InternInPlace;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyUnicode_InternFromString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, void> PyUnicode_InternImmortal;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, _PyObject*> PyUnicode_FromWideChar;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, ushort*, long, long> PyUnicode_AsWideChar;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, ushort*> PyUnicode_AsWideCharString;
    [Import] public delegate* unmanaged[Cdecl]<int, _PyObject*> PyUnicode_FromOrdinal;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*> PyUnicode_GetDefaultEncoding;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, sbyte*, _PyObject*> PyUnicode_Decode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, _PyObject*> PyUnicode_AsDecodedObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, _PyObject*> PyUnicode_AsDecodedUnicode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, _PyObject*> PyUnicode_AsEncodedObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, _PyObject*> PyUnicode_AsEncodedString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, _PyObject*> PyUnicode_AsEncodedUnicode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_BuildEncodingMap;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeUTF7;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, long*, _PyObject*> PyUnicode_DecodeUTF7Stateful;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeUTF8;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, long*, _PyObject*> PyUnicode_DecodeUTF8Stateful;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsUTF8String;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, sbyte*> PyUnicode_AsUTF8AndSize;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, int*, _PyObject*> PyUnicode_DecodeUTF32;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, int*, long*, _PyObject*> PyUnicode_DecodeUTF32Stateful;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsUTF32String;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, int*, _PyObject*> PyUnicode_DecodeUTF16;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, int*, long*, _PyObject*> PyUnicode_DecodeUTF16Stateful;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsUTF16String;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeUnicodeEscape;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsUnicodeEscapeString;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeRawUnicodeEscape;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsRawUnicodeEscapeString;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeLatin1;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsLatin1String;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeASCII;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsASCIIString;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, _PyObject*, sbyte*, _PyObject*> PyUnicode_DecodeCharmap;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyUnicode_AsCharmapString;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeMBCS;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, long*, _PyObject*> PyUnicode_DecodeMBCSStateful;
    [Import] public delegate* unmanaged[Cdecl]<int, sbyte*, long, sbyte*, long*, _PyObject*> PyUnicode_DecodeCodePageStateful;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_AsMBCSString;
    [Import] public delegate* unmanaged[Cdecl]<int, _PyObject*, sbyte*, _PyObject*> PyUnicode_EncodeCodePage;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*> PyUnicode_DecodeLocaleAndSize;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, _PyObject*> PyUnicode_DecodeLocale;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> PyUnicode_EncodeLocale;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> PyUnicode_FSConverter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> PyUnicode_FSDecoder;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyUnicode_DecodeFSDefault;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, _PyObject*> PyUnicode_DecodeFSDefaultAndSize;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicode_EncodeFSDefault;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyUnicode_Concat;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, _PyObject*, void> PyUnicode_Append;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, _PyObject*, void> PyUnicode_AppendAndDel;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, _PyObject*> PyUnicode_Split;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> PyUnicode_Splitlines;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyUnicode_Partition;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyUnicode_RPartition;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, _PyObject*> PyUnicode_RSplit;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, sbyte*, _PyObject*> PyUnicode_Translate;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyUnicode_Join;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, long, int, long> PyUnicode_Tailmatch;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, long, int, long> PyUnicode_Find;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, uint, long, long, int, long> PyUnicode_FindChar;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, long, long> PyUnicode_Count;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, long, _PyObject*> PyUnicode_Replace;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyUnicode_Compare;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyUnicode_CompareWithASCIIString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int, _PyObject*> PyUnicode_RichCompare;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyUnicode_Format;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyUnicode_Contains;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyUnicode_IsIdentifier;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, int> _PyUnicode_CheckConsistency;
    [Import] public delegate* unmanaged[Cdecl]<long, uint, _PyObject*> PyUnicode_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyUnicode_Ready;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> _PyUnicode_Copy;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*, long, long, long> PyUnicode_CopyCharacters;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*, long, long, void> _PyUnicode_FastCopyCharacters;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, uint, long> PyUnicode_Fill;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, uint, void> _PyUnicode_FastFill;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, _PyObject*> PyUnicode_FromUnicode;
    [Import] public delegate* unmanaged[Cdecl]<int, void*, long, _PyObject*> PyUnicode_FromKindAndData;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, _PyObject*> _PyUnicode_FromASCII;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, uint> _PyUnicode_FindMaxChar;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, ushort*> PyUnicode_AsUnicode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, ushort*> _PyUnicode_AsUnicode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, ushort*> PyUnicode_AsUnicodeAndSize;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, void> _PyUnicodeWriter_Init;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, long, uint, int> _PyUnicodeWriter_PrepareInternal;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, PyUnicode_Kind, int> _PyUnicodeWriter_PrepareKindInternal;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, uint, int> _PyUnicodeWriter_WriteChar;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*, int> _PyUnicodeWriter_WriteStr;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*, long, long, int> _PyUnicodeWriter_WriteSubstring;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, sbyte*, long, int> _PyUnicodeWriter_WriteASCIIString;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, sbyte*, long, int> _PyUnicodeWriter_WriteLatin1String;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*> _PyUnicodeWriter_Finish;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, void> _PyUnicodeWriter_Dealloc;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*, _PyObject*, long, long, int> _PyUnicode_FormatAdvancedWriter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyUnicode_AsUTF8;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, sbyte*, _PyObject*> PyUnicode_Encode;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, int, int, sbyte*, _PyObject*> PyUnicode_EncodeUTF7;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, int, sbyte*, _PyObject*> _PyUnicode_EncodeUTF7;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> _PyUnicode_AsUTF8String;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, _PyObject*> PyUnicode_EncodeUTF8;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, int, _PyObject*> PyUnicode_EncodeUTF32;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int, _PyObject*> _PyUnicode_EncodeUTF32;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, int, _PyObject*> PyUnicode_EncodeUTF16;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int, _PyObject*> _PyUnicode_EncodeUTF16;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, long*, _PyObject*> _PyUnicode_DecodeUnicodeEscapeStateful;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, long*, sbyte**, _PyObject*> _PyUnicode_DecodeUnicodeEscapeInternal;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, _PyObject*> PyUnicode_EncodeUnicodeEscape;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, _PyObject*> PyUnicode_EncodeRawUnicodeEscape;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, long*, _PyObject*> _PyUnicode_DecodeRawUnicodeEscapeStateful;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> _PyUnicode_AsLatin1String;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, _PyObject*> PyUnicode_EncodeLatin1;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> _PyUnicode_AsASCIIString;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, _PyObject*> PyUnicode_EncodeASCII;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, _PyObject*, sbyte*, _PyObject*> PyUnicode_EncodeCharmap;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, sbyte*, _PyObject*> _PyUnicode_EncodeCharmap;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, _PyObject*, sbyte*, _PyObject*> PyUnicode_TranslateCharmap;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, _PyObject*> PyUnicode_EncodeMBCS;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, sbyte*, sbyte*, int> PyUnicode_EncodeDecimal;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, long, _PyObject*> PyUnicode_TransformDecimalToASCII;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> _PyUnicode_TransformDecimalAndSpaceToASCII;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject**, long, _PyObject*> _PyUnicode_JoinArray;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, int> _PyUnicode_EqualToASCIIId;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> _PyUnicode_EqualToASCIIString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*, _PyObject*> _PyUnicode_XStrip;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, long, _PyObject*, long, long, long, sbyte*, _PyObject*, uint*, long> _PyUnicode_InsertThousandsGrouping;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsLowercase;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsUppercase;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsTitlecase;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsXidStart;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsXidContinue;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsWhitespace;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsLinebreak;
    [Import] public delegate* unmanaged[Cdecl]<uint, uint> _PyUnicode_ToLowercase;
    [Import] public delegate* unmanaged[Cdecl]<uint, uint> _PyUnicode_ToUppercase;
    [Import] public delegate* unmanaged[Cdecl]<uint, uint> _PyUnicode_ToTitlecase;
    [Import] public delegate* unmanaged[Cdecl]<uint, uint*, int> _PyUnicode_ToLowerFull;
    [Import] public delegate* unmanaged[Cdecl]<uint, uint*, int> _PyUnicode_ToTitleFull;
    [Import] public delegate* unmanaged[Cdecl]<uint, uint*, int> _PyUnicode_ToUpperFull;
    [Import] public delegate* unmanaged[Cdecl]<uint, uint*, int> _PyUnicode_ToFoldedFull;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsCaseIgnorable;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsCased;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_ToDecimalDigit;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_ToDigit;
    [Import] public delegate* unmanaged[Cdecl]<uint, Double> _PyUnicode_ToNumeric;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsDecimalDigit;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsDigit;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsNumeric;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsPrintable;
    [Import] public delegate* unmanaged[Cdecl]<uint, int> _PyUnicode_IsAlpha;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, int, int, _PyObject*> _PyUnicode_FormatLong;
    [Import] public delegate* unmanaged[Cdecl]<_Py_Identifier*, _PyObject*> _PyUnicode_FromId;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> _PyUnicode_EQ;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> _PyUnicode_WideCharString_Converter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> _PyUnicode_WideCharString_Opt_Converter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> _PyUnicode_ScanIdentifier;
    [Import] public delegate* unmanaged[Cdecl]<int, _PyObject*> PyLong_FromLong;
    [Import] public delegate* unmanaged[Cdecl]<uint, _PyObject*> PyLong_FromUnsignedLong;
    [Import] public delegate* unmanaged[Cdecl]<nuint, _PyObject*> PyLong_FromSize_t;
    [Import] public delegate* unmanaged[Cdecl]<long, _PyObject*> PyLong_FromSsize_t;
    [Import] public delegate* unmanaged[Cdecl]<Double, _PyObject*> PyLong_FromDouble;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyLong_AsLong;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int*, int> PyLong_AsLongAndOverflow;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyLong_AsSsize_t;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, nuint> PyLong_AsSize_t;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, uint> PyLong_AsUnsignedLong;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, uint> PyLong_AsUnsignedLongMask;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyLong_AsInt;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyLong_GetInfo;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> _PyLong_UnsignedShort_Converter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> _PyLong_UnsignedInt_Converter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> _PyLong_UnsignedLong_Converter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> _PyLong_UnsignedLongLong_Converter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, int> _PyLong_Size_t_Converter;
    [Import] public delegate* unmanaged[Cdecl]<_longobject*, long*, Double> _PyLong_Frexp;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, Double> PyLong_AsDouble;
    [Import] public delegate* unmanaged[Cdecl]<void*, _PyObject*> PyLong_FromVoidPtr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*> PyLong_AsVoidPtr;
    [Import] public delegate* unmanaged[Cdecl]<long, _PyObject*> PyLong_FromLongLong;
    [Import] public delegate* unmanaged[Cdecl]<ulong, _PyObject*> PyLong_FromUnsignedLongLong;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyLong_AsLongLong;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, ulong> PyLong_AsUnsignedLongLong;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, ulong> PyLong_AsUnsignedLongLongMask;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int*, long> PyLong_AsLongLongAndOverflow;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte**, int, _PyObject*> PyLong_FromString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> PyLong_FromUnicodeObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, int, _PyObject*> _PyLong_FromBytes;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyLong_Sign;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, nuint> _PyLong_NumBits;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> _PyLong_DivmodNear;
    [Import] public delegate* unmanaged[Cdecl]<byte*, nuint, int, int, _PyObject*> _PyLong_FromByteArray;
    [Import] public delegate* unmanaged[Cdecl]<_longobject*, byte*, nuint, int, int, int> _PyLong_AsByteArray;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> _PyLong_Format;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*, int, int, int> _PyLong_FormatWriter;
    [Import] public delegate* unmanaged[Cdecl]<_PyBytesWriter*, sbyte*, _PyObject*, int, int, sbyte*> _PyLong_FormatBytesWriter;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*, _PyObject*, long, long, int> _PyLong_FormatAdvancedWriter;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte**, int, uint> PyOS_strtoul;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte**, int, int> PyOS_strtol;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> _PyLong_GCD;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, nuint, _PyObject*> _PyLong_Rshift;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, nuint, _PyObject*> _PyLong_Lshift;
    [Import] public delegate* unmanaged[Cdecl]<long, _longobject*> _PyLong_New;
    [Import] public delegate* unmanaged[Cdecl]<_longobject*, _PyObject*> _PyLong_Copy;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> Py_IsTrue;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> Py_IsFalse;
    [Import] public delegate* unmanaged[Cdecl]<int, _PyObject*> PyBool_FromLong;
    [Import] public delegate* unmanaged[Cdecl]<Double> PyFloat_GetMax;
    [Import] public delegate* unmanaged[Cdecl]<Double> PyFloat_GetMin;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyFloat_GetInfo;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFloat_FromString;
    [Import] public delegate* unmanaged[Cdecl]<Double, _PyObject*> PyFloat_FromDouble;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, Double> PyFloat_AsDouble;
    [Import] public delegate* unmanaged[Cdecl]<Double, byte*, int, int> _PyFloat_Pack2;
    [Import] public delegate* unmanaged[Cdecl]<Double, byte*, int, int> _PyFloat_Pack4;
    [Import] public delegate* unmanaged[Cdecl]<Double, byte*, int, int> _PyFloat_Pack8;
    [Import] public delegate* unmanaged[Cdecl]<byte*, int, Double> _PyFloat_Unpack2;
    [Import] public delegate* unmanaged[Cdecl]<byte*, int, Double> _PyFloat_Unpack4;
    [Import] public delegate* unmanaged[Cdecl]<byte*, int, Double> _PyFloat_Unpack8;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, void> _PyFloat_DebugMallocStats;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*, _PyObject*, long, long, int> _PyFloat_FormatAdvancedWriter;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, Py_complex, Py_complex> _Py_c_sum;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, Py_complex, Py_complex> _Py_c_diff;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, Py_complex> _Py_c_neg;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, Py_complex, Py_complex> _Py_c_prod;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, Py_complex, Py_complex> _Py_c_quot;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, Py_complex, Py_complex> _Py_c_pow;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, Double> _Py_c_abs;
    [Import] public delegate* unmanaged[Cdecl]<Py_complex, _PyObject*> PyComplex_FromCComplex;
    [Import] public delegate* unmanaged[Cdecl]<Double, Double, _PyObject*> PyComplex_FromDoubles;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, Double> PyComplex_RealAsDouble;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, Double> PyComplex_ImagAsDouble;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, Py_complex> PyComplex_AsCComplex;
    [Import] public delegate* unmanaged[Cdecl]<_PyUnicodeWriter*, _PyObject*, _PyObject*, long, long, int> _PyComplex_FormatAdvancedWriter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyMemoryView_FromObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, int, _PyObject*> PyMemoryView_FromMemory;
    [Import] public delegate* unmanaged[Cdecl]<_PyBufferInfo*, _PyObject*> PyMemoryView_FromBuffer;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, sbyte, _PyObject*> PyMemoryView_GetContiguous;
    [Import] public delegate* unmanaged[Cdecl]<long, _PyObject*> PyTuple_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyTuple_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*> PyTuple_GetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*, int> PyTuple_SetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, _PyObject*> PyTuple_GetSlice;
    [Import] public delegate* unmanaged[Cdecl]<long, _PyObject*> PyList_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyList_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*> PyList_GetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*, int> PyList_SetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*, int> PyList_Insert;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyList_Append;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, _PyObject*> PyList_GetSlice;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, _PyObject*, int> PyList_SetSlice;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyList_Sort;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyList_Reverse;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyList_AsTuple;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyDict_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyDict_GetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyDict_GetItemWithError;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, int> PyDict_SetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyDict_DelItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> PyDict_Clear;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, _PyObject**, _PyObject**, int> PyDict_Next;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyDict_Keys;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyDict_Values;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyDict_Items;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyDict_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyDict_Copy;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyDict_Contains;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyDict_Update;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int, int> PyDict_Merge;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int, int> PyDict_MergeFromSeq2;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> PyDict_GetItemString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*, int> PyDict_SetItemString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyDict_DelItemString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*, _PyObject*> PyObject_GenericGetDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, _PyObject*> _PyDict_GetItem_KnownHash;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, _PyObject*> _PyDict_GetItemIdWithError;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> _PyDict_GetItemStringWithError;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyDict_SetDefault;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, long, int> _PyDict_SetItem_KnownHash;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, int> _PyDict_DelItem_KnownHash;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, delegate* unmanaged[Cdecl]<_PyObject*, int>, int> _PyDict_DelItemIf;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, _PyObject**, _PyObject**, long*, int> _PyDict_Next;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long, int> _PyDict_Contains_KnownHash;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, int> _PyDict_ContainsId;
    [Import] public delegate* unmanaged[Cdecl]<long, _PyObject*> _PyDict_NewPresized;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _PyDict_MaybeUntrack;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyDict_HasOnlyStringKeys;
    [Import] public delegate* unmanaged[Cdecl]<PyDictObject*, long> _PyDict_SizeOf;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> _PyDict_Pop;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int, int> _PyDict_MergeEx;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, _PyObject*, int> _PyDict_SetItemId;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _Py_Identifier*, int> _PyDict_DelItemId;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, void> _PyDict_DebugMallocStats;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyTypeObject*, _PyObject*> _PyDictView_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> _PyDictView_Intersect;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, _PyObject**, long*, int> _PySet_NextEntry;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> _PySet_Update;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PySet_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFrozenSet_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PySet_Add;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PySet_Clear;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PySet_Contains;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PySet_Discard;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PySet_Pop;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PySet_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*>> PyCFunction_GetFunction;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyCFunction_GetSelf;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyCFunction_GetFlags;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyCFunction_Call;
    [Import] public delegate* unmanaged[Cdecl]<PyMethodDef*, _PyObject*, _PyObject*> PyCFunction_New;
    [Import] public delegate* unmanaged[Cdecl]<PyMethodDef*, _PyObject*, _PyObject*, _PyObject*> PyCFunction_NewEx;
    [Import] public delegate* unmanaged[Cdecl]<PyMethodDef*, _PyObject*, _PyObject*, _PyTypeObject*, _PyObject*> PyCMethod_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyModule_NewObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyModule_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyModule_GetDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyModule_GetNameObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyModule_GetName;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyModule_GetFilename;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyModule_GetFilenameObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _PyModule_Clear;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _PyModule_ClearDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyModuleSpec_IsInitializing;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, PyModuleDef*> PyModule_GetDef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void*> PyModule_GetState;
    [Import] public delegate* unmanaged[Cdecl]<PyModuleDef*, _PyObject*> PyModuleDef_Init;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyFunction_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyFunction_NewWithQualName;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFunction_GetCode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFunction_GetGlobals;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFunction_GetModule;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFunction_GetDefaults;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyFunction_SetDefaults;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFunction_GetKwDefaults;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyFunction_SetKwDefaults;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFunction_GetClosure;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyFunction_SetClosure;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyFunction_GetAnnotations;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyFunction_SetAnnotations;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject**, nuint, _PyObject*, _PyObject*> _PyFunction_Vectorcall;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyClassMethod_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyStaticMethod_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyMethod_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyMethod_Function;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyMethod_Self;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyInstanceMethod_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyInstanceMethod_Function;
    [Import] public delegate* unmanaged[Cdecl]<int, sbyte*, sbyte*, int, sbyte*, sbyte*, sbyte*, int, _PyObject*> PyFile_FromFd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> PyFile_GetLine;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int, int> PyFile_WriteObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, int> PyFile_WriteString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyObject_AsFileDescriptor;
    [Import] public delegate* unmanaged[Cdecl]<int, int, int, int, int, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, int, _PyObject*, PyCodeObject*> PyCode_New;
    [Import] public delegate* unmanaged[Cdecl]<int, int, int, int, int, int, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*, int, _PyObject*, PyCodeObject*> PyCode_NewWithPosOnlyArgs;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, int, PyCodeObject*> PyCode_NewEmpty;
    [Import] public delegate* unmanaged[Cdecl]<PyCodeObject*, int, int> PyCode_Addr2Line;
    [Import] public delegate* unmanaged[Cdecl]<int, _line_offsets*, int> _PyCode_CheckLineNumber;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> _PyCode_ConstantKey;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*> PyCode_Optimize;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, void**, int> _PyCode_GetExtra;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, void*, int> _PyCode_SetExtra;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, int> PyFrame_GetLineNumber;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, PyCodeObject*> PyFrame_GetCode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PySlice_New;
    [Import] public delegate* unmanaged[Cdecl]<long, long, _PyObject*> _PySlice_FromIndices;
    [Import] public delegate* unmanaged[Cdecl]<PySliceObject*, _PyObject*, _PyObject**, _PyObject**, _PyObject**, int> _PySlice_GetLongIndices;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long*, long*, long*, int> PySlice_GetIndices;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long*, long*, long*, long*, int> PySlice_GetIndicesEx;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, long*, long*, int> PySlice_Unpack;
    [Import] public delegate* unmanaged[Cdecl]<long, long*, long*, long, long> PySlice_AdjustIndices;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyCell_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyCell_Get;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyCell_Set;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PySeqIter_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyCallIter_New;
    [Import] public delegate* unmanaged[Cdecl]<PyStatus> PyStatus_Ok;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, PyStatus> PyStatus_Error;
    [Import] public delegate* unmanaged[Cdecl]<PyStatus> PyStatus_NoMemory;
    [Import] public delegate* unmanaged[Cdecl]<int, PyStatus> PyStatus_Exit;
    [Import] public delegate* unmanaged[Cdecl]<PyStatus, int> PyStatus_IsError;
    [Import] public delegate* unmanaged[Cdecl]<PyStatus, int> PyStatus_IsExit;
    [Import] public delegate* unmanaged[Cdecl]<PyStatus, int> PyStatus_Exception;
    [Import] public delegate* unmanaged[Cdecl]<PyWideStringList*, ushort*, PyStatus> PyWideStringList_Append;
    [Import] public delegate* unmanaged[Cdecl]<PyWideStringList*, long, ushort*, PyStatus> PyWideStringList_Insert;
    [Import] public delegate* unmanaged[Cdecl]<PyPreConfig*, void> PyPreConfig_InitPythonConfig;
    [Import] public delegate* unmanaged[Cdecl]<PyPreConfig*, void> PyPreConfig_InitIsolatedConfig;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, void> PyConfig_InitPythonConfig;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, void> PyConfig_InitIsolatedConfig;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, void> PyConfig_Clear;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, ushort**, ushort*, PyStatus> PyConfig_SetString;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, ushort**, sbyte*, PyStatus> PyConfig_SetBytesString;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, PyStatus> PyConfig_Read;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, long, sbyte**, PyStatus> PyConfig_SetBytesArgv;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, long, ushort**, PyStatus> PyConfig_SetArgv;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, PyWideStringList*, long, ushort**, PyStatus> PyConfig_SetWideStringList;
    [Import] public delegate* unmanaged[Cdecl]<int*, ushort***, void> Py_GetArgcArgv;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*> PyInterpreterState_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, void> PyInterpreterState_Clear;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, void> PyInterpreterState_Delete;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*> PyInterpreterState_Get;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, _PyObject*> PyInterpreterState_GetDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, long> PyInterpreterState_GetID;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, PyModuleDef*, int> PyState_AddModule;
    [Import] public delegate* unmanaged[Cdecl]<PyModuleDef*, int> PyState_RemoveModule;
    [Import] public delegate* unmanaged[Cdecl]<PyModuleDef*, _PyObject*> PyState_FindModule;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, _PyThreadState*> PyThreadState_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, void> PyThreadState_Clear;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, void> PyThreadState_Delete;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*> PyThreadState_Get;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, _PyThreadState*> PyThreadState_Swap;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyThreadState_GetDict;
    [Import] public delegate* unmanaged[Cdecl]<uint, _PyObject*, int> PyThreadState_SetAsyncExc;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, _PyInterpreterState*> PyThreadState_GetInterpreter;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, _frame*> PyThreadState_GetFrame;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, ulong> PyThreadState_GetID;
    [Import] public delegate* unmanaged[Cdecl]<PyGILState_STATE> PyGILState_Ensure;
    [Import] public delegate* unmanaged[Cdecl]<PyGILState_STATE, void> PyGILState_Release;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*> PyGILState_GetThisThreadState;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, int> _PyInterpreterState_RequiresIDRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, int, void> _PyInterpreterState_RequireIDRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, _PyObject*> _PyInterpreterState_GetMainModule;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, _PyThreadState*> _PyThreadState_Prealloc;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*> _PyThreadState_UncheckedGet;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, _PyObject*> _PyThreadState_GetDict;
    [Import] public delegate* unmanaged[Cdecl]<int> PyGILState_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*> _PyGILState_GetInterpreterStateUnsafe;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> _PyThread_CurrentFrames;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> _PyThread_CurrentExceptions;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*> PyInterpreterState_Main;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*> PyInterpreterState_Head;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, _PyInterpreterState*> PyInterpreterState_Next;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, _PyThreadState*> PyInterpreterState_ThreadHead;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, _PyThreadState*> PyThreadState_Next;
    [Import] public delegate* unmanaged[Cdecl]<void> PyThreadState_DeleteCurrent;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, delegate* unmanaged[Cdecl]<_PyThreadState*, _frame*, int, _PyObject*>> _PyInterpreterState_GetEvalFrameFunc;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, delegate* unmanaged[Cdecl]<_PyThreadState*, _frame*, int, _PyObject*>, void> _PyInterpreterState_SetEvalFrameFunc;
    [Import] public delegate* unmanaged[Cdecl]<_PyInterpreterState*, PyConfig*> _PyInterpreterState_GetConfig;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, int> _PyInterpreterState_GetConfigCopy;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*, int> _PyInterpreterState_SetConfig;
    [Import] public delegate* unmanaged[Cdecl]<PyConfig*> _Py_GetConfig;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _xid*, int> _PyObject_GetCrossInterpreterData;
    [Import] public delegate* unmanaged[Cdecl]<_xid*, _PyObject*> _PyCrossInterpreterData_NewObject;
    [Import] public delegate* unmanaged[Cdecl]<_xid*, void> _PyCrossInterpreterData_Release;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyObject_CheckCrossInterpreterData;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, delegate* unmanaged[Cdecl]<_PyObject*, _xid*, int>, int> _PyCrossInterpreterData_RegisterClass;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, delegate* unmanaged[Cdecl]<_PyObject*, _xid*, int>> _PyCrossInterpreterData_Lookup;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_CallNoArgs;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyObject_Call;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyObject_CallObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_Type;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyObject_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyObject_GetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, int> PyObject_SetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyObject_DelItemString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyObject_DelItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte**, long*, int> PyObject_AsCharBuffer;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyObject_CheckReadBuffer;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void**, long*, int> PyObject_AsReadBuffer;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void**, long*, int> PyObject_AsWriteBuffer;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyObject_Format;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_GetIter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyObject_GetAIter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyIter_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyAIter_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyIter_Next;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject**, PySendResult> PyIter_Send;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyNumber_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Add;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Subtract;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Multiply;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_MatrixMultiply;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_FloorDivide;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_TrueDivide;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Remainder;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Divmod;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyNumber_Power;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyNumber_Negative;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyNumber_Positive;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyNumber_Absolute;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyNumber_Invert;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Lshift;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Rshift;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_And;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Xor;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_Or;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyIndex_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyNumber_Index;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long> PyNumber_AsSsize_t;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyNumber_Long;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyNumber_Float;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceAdd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceSubtract;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceMultiply;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceMatrixMultiply;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceFloorDivide;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceTrueDivide;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceRemainder;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyNumber_InPlacePower;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceLshift;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceRshift;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceAnd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceXor;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyNumber_InPlaceOr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> PyNumber_ToBase;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PySequence_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PySequence_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PySequence_Concat;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*> PySequence_Repeat;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*> PySequence_GetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, _PyObject*> PySequence_GetSlice;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*, int> PySequence_SetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PySequence_DelItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, _PyObject*, int> PySequence_SetSlice;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, long, int> PySequence_DelSlice;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PySequence_Tuple;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PySequence_List;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> PySequence_Fast;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long> PySequence_Count;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PySequence_Contains;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, long> PySequence_Index;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PySequence_InPlaceConcat;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*> PySequence_InPlaceRepeat;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyMapping_Check;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long> PyMapping_Size;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyMapping_HasKeyString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyMapping_HasKey;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyMapping_Keys;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyMapping_Values;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyMapping_Items;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> PyMapping_GetItemString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*, int> PyMapping_SetItemString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyObject_IsInstance;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyObject_IsSubclass;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, _PyObject*> PyGen_New;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, _PyObject*, _PyObject*, _PyObject*> PyGen_NewWithQualName;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> _PyGen_SetStopIterationValue;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, int> _PyGen_FetchStopIterationValue;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> _PyGen_Finalize;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, _PyObject*, _PyObject*, _PyObject*> PyCoro_New;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, _PyObject*, _PyObject*, _PyObject*> PyAsyncGen_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, PyMethodDef*, _PyObject*> PyDescr_NewMethod;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, PyMethodDef*, _PyObject*> PyDescr_NewClassMethod;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, PyMemberDef*, _PyObject*> PyDescr_NewMember;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, PyGetSetDef*, _PyObject*> PyDescr_NewGetSet;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _PyWrapperBase*, void*, _PyObject*> PyDescr_NewWrapper;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyDescr_IsData;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyDictProxy_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyWrapper_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> Py_GenericAlias;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> _PyWarnings_Init;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, long, int> PyErr_WarnEx;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, int, _PyObject*, _PyObject*, int> PyErr_WarnExplicitObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, int, sbyte*, _PyObject*, int> PyErr_WarnExplicit;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyWeakref_NewRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyWeakref_NewProxy;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyWeakref_GetObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyWeakReference*, long> _PyWeakref_GetWeakrefCount;
    [Import] public delegate* unmanaged[Cdecl]<_PyWeakReference*, void> _PyWeakref_ClearRef;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, PyStructSequence_Desc*, void> PyStructSequence_InitType;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, PyStructSequence_Desc*, int> PyStructSequence_InitType2;
    [Import] public delegate* unmanaged[Cdecl]<PyStructSequence_Desc*, _PyTypeObject*> PyStructSequence_NewType;
    [Import] public delegate* unmanaged[Cdecl]<_PyTypeObject*, _PyObject*> PyStructSequence_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*, void> PyStructSequence_SetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, _PyObject*> PyStructSequence_GetItem;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> _PyNamespace_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> PyErr_SetNone;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, void> PyErr_SetObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, void> PyErr_SetString;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyErr_Occurred;
    [Import] public delegate* unmanaged[Cdecl]<void> PyErr_Clear;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, _PyObject**, _PyObject**, void> PyErr_Fetch;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, void> PyErr_Restore;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, _PyObject**, _PyObject**, void> PyErr_GetExcInfo;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, void> PyErr_SetExcInfo;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, void> Py_FatalError;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyErr_GivenExceptionMatches;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyErr_ExceptionMatches;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject**, _PyObject**, _PyObject**, void> PyErr_NormalizeException;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyException_SetTraceback;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyException_GetTraceback;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyException_GetCause;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, void> PyException_SetCause;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyException_GetContext;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, void> PyException_SetContext;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyExceptionClass_Name;
    [Import] public delegate* unmanaged[Cdecl]<int> PyErr_BadArgument;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyErr_NoMemory;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyErr_SetFromErrno;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyErr_SetFromErrnoWithFilenameObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyErr_SetFromErrnoWithFilenameObjects;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, _PyObject*> PyErr_SetFromErrnoWithFilename;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, _PyObject*> PyErr_FormatV;
    [Import] public delegate* unmanaged[Cdecl]<int, sbyte*, _PyObject*> PyErr_SetFromWindowsErrWithFilename;
    [Import] public delegate* unmanaged[Cdecl]<int, _PyObject*> PyErr_SetFromWindowsErr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*, _PyObject*> PyErr_SetExcFromWindowsErrWithFilenameObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*, _PyObject*, _PyObject*> PyErr_SetExcFromWindowsErrWithFilenameObjects;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, sbyte*, _PyObject*> PyErr_SetExcFromWindowsErrWithFilename;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int, _PyObject*> PyErr_SetExcFromWindowsErr;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*> PyErr_SetImportErrorSubclass;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyErr_SetImportError;
    [Import] public delegate* unmanaged[Cdecl]<void> PyErr_BadInternalCall;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int, void> _PyErr_BadInternalCall;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, _PyObject*, _PyObject*> PyErr_NewException;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, _PyObject*, _PyObject*, _PyObject*> PyErr_NewExceptionWithDoc;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> PyErr_WriteUnraisable;
    [Import] public delegate* unmanaged[Cdecl]<int> PyErr_CheckSignals;
    [Import] public delegate* unmanaged[Cdecl]<void> PyErr_SetInterrupt;
    [Import] public delegate* unmanaged[Cdecl]<int, int> PyErr_SetInterruptEx;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int, void> PyErr_SyntaxLocation;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int, int, void> PyErr_SyntaxLocationEx;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int, _PyObject*> PyErr_ProgramText;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, long, long, long, sbyte*, _PyObject*> PyUnicodeDecodeError_Create;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeEncodeError_GetEncoding;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeDecodeError_GetEncoding;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeEncodeError_GetObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeDecodeError_GetObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeTranslateError_GetObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, int> PyUnicodeEncodeError_GetStart;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, int> PyUnicodeDecodeError_GetStart;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, int> PyUnicodeTranslateError_GetStart;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PyUnicodeEncodeError_SetStart;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PyUnicodeDecodeError_SetStart;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PyUnicodeTranslateError_SetStart;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, int> PyUnicodeEncodeError_GetEnd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, int> PyUnicodeDecodeError_GetEnd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long*, int> PyUnicodeTranslateError_GetEnd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PyUnicodeEncodeError_SetEnd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PyUnicodeDecodeError_SetEnd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, long, int> PyUnicodeTranslateError_SetEnd;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeEncodeError_GetReason;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeDecodeError_GetReason;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyUnicodeTranslateError_GetReason;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyUnicodeEncodeError_SetReason;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyUnicodeDecodeError_SetReason;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, int> PyUnicodeTranslateError_SetReason;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, nuint, sbyte*, sbyte*, int> PyOS_vsnprintf;
    [Import] public delegate* unmanaged[Cdecl]<void> PyThread_init_thread;
    [Import] public delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<void*, void>, void*, uint> PyThread_start_new_thread;
    [Import] public delegate* unmanaged[Cdecl]<void> PyThread_exit_thread;
    [Import] public delegate* unmanaged[Cdecl]<uint> PyThread_get_thread_ident;
    [Import] public delegate* unmanaged[Cdecl]<uint> PyThread_get_thread_native_id;
    [Import] public delegate* unmanaged[Cdecl]<void*> PyThread_allocate_lock;
    [Import] public delegate* unmanaged[Cdecl]<void*, void> PyThread_free_lock;
    [Import] public delegate* unmanaged[Cdecl]<void*, int, int> PyThread_acquire_lock;
    [Import] public delegate* unmanaged[Cdecl]<void*, long, int, PyLockStatus> PyThread_acquire_lock_timed;
    [Import] public delegate* unmanaged[Cdecl]<void*, void> PyThread_release_lock;
    [Import] public delegate* unmanaged[Cdecl]<nuint> PyThread_get_stacksize;
    [Import] public delegate* unmanaged[Cdecl]<nuint, int> PyThread_set_stacksize;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyThread_GetInfo;
    [Import] public delegate* unmanaged[Cdecl]<int> PyThread_create_key;
    [Import] public delegate* unmanaged[Cdecl]<int, void> PyThread_delete_key;
    [Import] public delegate* unmanaged[Cdecl]<int, void*, int> PyThread_set_key_value;
    [Import] public delegate* unmanaged[Cdecl]<int, void*> PyThread_get_key_value;
    [Import] public delegate* unmanaged[Cdecl]<int, void> PyThread_delete_key_value;
    [Import] public delegate* unmanaged[Cdecl]<void> PyThread_ReInitTLS;
    [Import] public delegate* unmanaged[Cdecl]<_Py_tss_t*> PyThread_tss_alloc;
    [Import] public delegate* unmanaged[Cdecl]<_Py_tss_t*, void> PyThread_tss_free;
    [Import] public delegate* unmanaged[Cdecl]<_Py_tss_t*, int> PyThread_tss_is_created;
    [Import] public delegate* unmanaged[Cdecl]<_Py_tss_t*, int> PyThread_tss_create;
    [Import] public delegate* unmanaged[Cdecl]<_Py_tss_t*, void> PyThread_tss_delete;
    [Import] public delegate* unmanaged[Cdecl]<_Py_tss_t*, void*, int> PyThread_tss_set;
    [Import] public delegate* unmanaged[Cdecl]<_Py_tss_t*, void*> PyThread_tss_get;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyContext_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyContext_Copy;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyContext_CopyCurrent;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyContext_Enter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyContext_Exit;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, _PyObject*> PyContextVar_New;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject**, int> PyContextVar_Get;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> PyContextVar_Set;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, int> PyContextVar_Reset;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> _PyContext_NewHamtForTests;
    [Import] public delegate* unmanaged[Cdecl]<int, int, int> PyCompile_OpcodeStackEffect;
    [Import] public delegate* unmanaged[Cdecl]<int, int, int, int> PyCompile_OpcodeStackEffectWithJump;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, int, _PyObject*> Py_CompileString;
    [Import] public delegate* unmanaged[Cdecl]<void> PyErr_Print;
    [Import] public delegate* unmanaged[Cdecl]<int, void> PyErr_PrintEx;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, void> PyErr_Display;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, PyCompilerFlags*, int> PyRun_SimpleStringFlags;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, _PyObject*, int, PyCompilerFlags*, int> _PyRun_SimpleFileObject;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, PyCompilerFlags*, int> PyRun_AnyFileExFlags;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, _PyObject*, int, PyCompilerFlags*, int> _PyRun_AnyFileObject;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, PyCompilerFlags*, int> PyRun_SimpleFileExFlags;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, PyCompilerFlags*, int> PyRun_InteractiveOneFlags;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, _PyObject*, PyCompilerFlags*, int> PyRun_InteractiveOneObject;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, PyCompilerFlags*, int> PyRun_InteractiveLoopFlags;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, _PyObject*, PyCompilerFlags*, int> _PyRun_InteractiveLoopObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int, _PyObject*, _PyObject*, PyCompilerFlags*, _PyObject*> PyRun_StringFlags;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, _PyObject*, _PyObject*, int, PyCompilerFlags*, _PyObject*> PyRun_FileExFlags;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, int, PyCompilerFlags*, int, _PyObject*> Py_CompileStringExFlags;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, int, PyCompilerFlags*, int, _PyObject*> Py_CompileStringObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*, sbyte*, PyCompilerFlags*, _PyObject**, sbyte*> _Py_SourceAsString;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int, _PyObject*, _PyObject*, _PyObject*> PyRun_String;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int> PyRun_AnyFile;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, int> PyRun_AnyFileEx;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, PyCompilerFlags*, int> PyRun_AnyFileFlags;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int> PyRun_SimpleString;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int> PyRun_SimpleFile;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, int> PyRun_SimpleFileEx;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int> PyRun_InteractiveOne;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int> PyRun_InteractiveLoop;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, _PyObject*, _PyObject*, _PyObject*> PyRun_File;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, _PyObject*, _PyObject*, int, _PyObject*> PyRun_FileEx;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, sbyte*, int, _PyObject*, _PyObject*, PyCompilerFlags*, _PyObject*> PyRun_FileFlags;
    [Import] public delegate* unmanaged[Cdecl]<_iobuf*, _iobuf*, sbyte*, sbyte*> PyOS_Readline;
    [Import] public delegate* unmanaged[Cdecl]<void> Py_Initialize;
    [Import] public delegate* unmanaged[Cdecl]<int, void> Py_InitializeEx;
    [Import] public delegate* unmanaged[Cdecl]<void> Py_Finalize;
    [Import] public delegate* unmanaged[Cdecl]<int> Py_FinalizeEx;
    [Import] public delegate* unmanaged[Cdecl]<int> Py_IsInitialized;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*> Py_NewInterpreter;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, void> Py_EndInterpreter;
    [Import] public delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<void>, int> Py_AtExit;
    [Import] public delegate* unmanaged[Cdecl]<int, void> Py_Exit;
    [Import] public delegate* unmanaged[Cdecl]<int, ushort**, int> Py_Main;
    [Import] public delegate* unmanaged[Cdecl]<int, sbyte**, int> Py_BytesMain;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, void> Py_SetProgramName;
    [Import] public delegate* unmanaged[Cdecl]<ushort*> Py_GetProgramName;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, void> Py_SetPythonHome;
    [Import] public delegate* unmanaged[Cdecl]<ushort*> Py_GetPythonHome;
    [Import] public delegate* unmanaged[Cdecl]<ushort*> Py_GetProgramFullPath;
    [Import] public delegate* unmanaged[Cdecl]<ushort*> Py_GetPrefix;
    [Import] public delegate* unmanaged[Cdecl]<ushort*> Py_GetExecPrefix;
    [Import] public delegate* unmanaged[Cdecl]<ushort*> Py_GetPath;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, void> Py_SetPath;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*> Py_GetVersion;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*> Py_GetPlatform;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*> Py_GetCopyright;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*> Py_GetCompiler;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*> Py_GetBuildInfo;
    [Import] public delegate* unmanaged[Cdecl]<int, delegate* unmanaged[Cdecl]<int, void>> PyOS_getsig;
    [Import] public delegate* unmanaged[Cdecl]<int, delegate* unmanaged[Cdecl]<int, void>, delegate* unmanaged[Cdecl]<int, void>> PyOS_setsig;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyEval_CallObjectWithKeywords;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyEval_GetBuiltins;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyEval_GetGlobals;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyEval_GetLocals;
    [Import] public delegate* unmanaged[Cdecl]<_frame*> PyEval_GetFrame;
    [Import] public delegate* unmanaged[Cdecl]<delegate* unmanaged[Cdecl]<void*, int>, void*, int> Py_AddPendingCall;
    [Import] public delegate* unmanaged[Cdecl]<int> Py_MakePendingCalls;
    [Import] public delegate* unmanaged[Cdecl]<int, void> Py_SetRecursionLimit;
    [Import] public delegate* unmanaged[Cdecl]<int> Py_GetRecursionLimit;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int> Py_EnterRecursiveCall;
    [Import] public delegate* unmanaged[Cdecl]<void> Py_LeaveRecursiveCall;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyEval_GetFuncName;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, sbyte*> PyEval_GetFuncDesc;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, _PyObject*> PyEval_EvalFrame;
    [Import] public delegate* unmanaged[Cdecl]<_frame*, int, _PyObject*> PyEval_EvalFrameEx;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*> PyEval_SaveThread;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, void> PyEval_RestoreThread;
    [Import] public delegate* unmanaged[Cdecl]<int> PyEval_ThreadsInitialized;
    [Import] public delegate* unmanaged[Cdecl]<void> PyEval_InitThreads;
    [Import] public delegate* unmanaged[Cdecl]<void> PyEval_AcquireLock;
    [Import] public delegate* unmanaged[Cdecl]<void> PyEval_ReleaseLock;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, void> PyEval_AcquireThread;
    [Import] public delegate* unmanaged[Cdecl]<_PyThreadState*, void> PyEval_ReleaseThread;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PySys_GetObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, int> PySys_SetObject;
    [Import] public delegate* unmanaged[Cdecl]<int, ushort**, void> PySys_SetArgv;
    [Import] public delegate* unmanaged[Cdecl]<int, ushort**, int, void> PySys_SetArgvEx;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, void> PySys_SetPath;
    [Import] public delegate* unmanaged[Cdecl]<void> PySys_ResetWarnOptions;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, void> PySys_AddWarnOption;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, void> PySys_AddWarnOptionUnicode;
    [Import] public delegate* unmanaged[Cdecl]<int> PySys_HasWarnOptions;
    [Import] public delegate* unmanaged[Cdecl]<ushort*, void> PySys_AddXOption;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PySys_GetXOptions;
    [Import] public delegate* unmanaged[Cdecl]<int> PyImport_GetMagicNumber;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*> PyImport_GetMagicTag;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, _PyObject*> PyImport_ExecCodeModule;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, sbyte*, _PyObject*> PyImport_ExecCodeModuleEx;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, sbyte*, sbyte*, _PyObject*> PyImport_ExecCodeModuleWithPathnames;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*, _PyObject*> PyImport_ExecCodeModuleObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*> PyImport_GetModuleDict;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyImport_GetModule;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyImport_AddModuleObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyImport_AddModule;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyImport_ImportModule;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*> PyImport_ImportModuleNoBlock;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, _PyObject*, _PyObject*, _PyObject*, int, _PyObject*> PyImport_ImportModuleLevel;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*, int, _PyObject*> PyImport_ImportModuleLevelObject;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyImport_GetImporter;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyImport_Import;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*> PyImport_ReloadModule;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, int> PyImport_ImportFrozenModuleObject;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, int> PyImport_ImportFrozenModule;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, delegate* unmanaged[Cdecl]<_PyObject*>, int> PyImport_AppendInittab;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject*> PyEval_EvalCode;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*, _PyObject**, int, _PyObject**, int, _PyObject**, int, _PyObject*, _PyObject*, _PyObject*> PyEval_EvalCodeEx;
    [Import] public delegate* unmanaged[Cdecl]<_PyObject*, _PyObject*, _PyObject*> _PyEval_CallTracing;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte**, _PyObject*, Double> PyOS_string_to_double;
    [Import] public delegate* unmanaged[Cdecl]<Double, sbyte, int, int, int*, sbyte*> PyOS_double_to_string;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, long, sbyte*, _PyObject*, void*, delegate* unmanaged[Cdecl]<sbyte*, long, void*, _PyObject*>, _PyObject*> _Py_string_to_number_with_underscores;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte**, Double> _Py_parse_inf_or_nan;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, long, int> PyOS_mystrnicmp;
    [Import] public delegate* unmanaged[Cdecl]<sbyte*, sbyte*, int> PyOS_mystricmp;
}
#pragma warning restore CS0649
